version: "3"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: financial_db
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: postgres
